// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/kelseyhightower/envconfig"
	"github.com/remove158/chula-sso/cmd/handlers"
	"github.com/remove158/chula-sso/cmd/routes"
	"github.com/remove158/chula-sso/internal/services"
)

// Injectors from wire.go:

func InitializeEvent() *Server {
	engine := InitializeGin()
	authService := services.NewAuthService()
	authHandler := handlers.NewAuthHandler(authService)
	authRoute := routes.NewAuthRoute(authHandler, engine)
	server := InitializeServer(engine, authRoute)
	return server
}

// wire.go:

type Server struct {
	AuthRoute routes.IAuthRoute
	Gin       *gin.Engine
	Config    Setting
}

type Setting struct {
	PORT string `envconfig:"PORT" default:"8080"`
}

func InitializeServer(gin2 *gin.Engine,
	authRoute routes.IAuthRoute,
) *Server {

	var config Setting
	envconfig.Process("", &config)

	return &Server{
		Gin:       gin2,
		AuthRoute: authRoute,
		Config:    config,
	}
}

func InitializeGin() *gin.Engine {
	return gin.Default()
}
